---
title: "The best post ever"
date: 2018-06-25
---

title: The best GitHub Pages site ever
author: EC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Test site for GitHub learning lab

# social links
twitter_username: campbellatlarge
github_username:  campbellita

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
